version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: song-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=tbarry
      - POSTGRES_PASSWORD=duxdYllH
      - POSTGRES_DB=songdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: song-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=tbarry
      - DB_PASSWORD=duxdYllH
      - DB_NAME=songdb
      - DB_PORT=5432
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: song-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    name: songmanager_app-network

volumes:
  postgres_data: